services:
  - type: web
    name: startupconnect
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mydevsite.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: DATABASE_URL
        fromDatabase:
          name: startupconnect-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"

databases:
  - name: startupconnect-db
    databaseName: startupconnect
    user: startupconnect
