# Generated by Django 4.2.20 on 2025-08-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_investorprofile_delete_project_delete_service_and_more"),
    ]

    operations = []
