# Generated by Django 4.2.20 on 2025-08-26 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_auto_20250826_1859"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start_datetime"]},
        ),
        migrations.AlterModelOptions(
            name="founderprofile",
            options={"verbose_name": "Founder Profile (Legacy)"},
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={"ordering": ["name"], "verbose_name_plural": "Industries"},
        ),
        migrations.AlterModelOptions(
            name="investorprofile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="registration_url",
            new_name="meeting_url",
        ),
        migrations.RenameField(
            model_name="investorprofile",
            old_name="company_name",
            new_name="fund_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="investorprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="investorprofile",
            name="focus_industries",
        ),
        migrations.RemoveField(
            model_name="investorprofile",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="investorprofile",
            name="website",
        ),
        migrations.AddField(
            model_name="event",
            name="agenda",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="gallery_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_virtual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="sponsors",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="target_audience",
            field=models.JSONField(
                default=list, help_text="founders, investors, advisors, community"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="industry",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="industry",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="fund_size",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="geographic_focus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("global", "Global"),
                    ("north_america", "North America"),
                    ("latin_america", "Latin America"),
                    ("europe", "Europe"),
                    ("asia", "Asia"),
                    ("africa", "Africa"),
                    ("local", "Local Market Only"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="investment_stages",
            field=models.JSONField(
                default=list, help_text="Etapas de inversión preferidas"
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="investments_per_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="is_accepting_pitches",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="notable_investments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="portfolio_companies_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="sweet_spot",
            field=models.TextField(blank=True, help_text="Sweet spot de inversiones"),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="thesis",
            field=models.TextField(blank=True, help_text="Tesis de inversión"),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="typical_investment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("networking", "Networking Mixer"),
                    ("pitch_night", "Pitch Night"),
                    ("panel", "Panel Discussion"),
                    ("workshop", "Workshop"),
                    ("breakfast", "Founders Breakfast"),
                    ("demo_day", "Demo Day"),
                    ("investor_day", "Investor Day"),
                    ("conference", "Conference"),
                    ("webinar", "Webinar"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="investor_type",
            field=models.CharField(
                choices=[
                    ("angel", "Angel Investor"),
                    ("vc_fund", "VC Fund"),
                    ("corporate_vc", "Corporate VC"),
                    ("family_office", "Family Office"),
                    ("accelerator", "Accelerator"),
                    ("government", "Government Fund"),
                    ("strategic", "Strategic Investor"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "user")},
            },
        ),
    ]
