# Generated by Django 4.2.20 on 2025-08-26 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_event_options_alter_founderprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("founder", "Founder"),
                            ("investor", "Investor"),
                            ("advisor", "Advisor"),
                            ("community", "Community Member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("show_contact_info", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "tagline",
                    models.CharField(
                        help_text="Descripción en una línea", max_length=150
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción detallada de la startup"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="startup_logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="startup_covers/"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("idea", "Idea Stage"),
                            ("prototype", "Prototype"),
                            ("mvp", "MVP"),
                            ("early_traction", "Early Traction"),
                            ("growth", "Growth"),
                            ("scale", "Scale"),
                            ("exit", "Exit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "revenue_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_revenue", "No Revenue"),
                            ("pre_revenue", "Pre-Revenue"),
                            ("early_revenue", "Early Revenue ($1K-$10K MRR)"),
                            ("growing_revenue", "Growing Revenue ($10K-$100K MRR)"),
                            ("scale_revenue", "Scale Revenue ($100K+ MRR)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("founded_date", models.DateField(blank=True, null=True)),
                ("employees_count", models.IntegerField(blank=True, null=True)),
                (
                    "problem_statement",
                    models.TextField(blank=True, help_text="¿Qué problema resuelven?"),
                ),
                (
                    "solution_description",
                    models.TextField(blank=True, help_text="¿Cómo lo resuelven?"),
                ),
                (
                    "market_size",
                    models.TextField(blank=True, help_text="Tamaño del mercado"),
                ),
                (
                    "business_model",
                    models.TextField(blank=True, help_text="Modelo de negocio"),
                ),
                (
                    "competitive_advantage",
                    models.TextField(blank=True, help_text="Ventaja competitiva"),
                ),
                ("sub_industry", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("monthly_users", models.IntegerField(blank=True, null=True)),
                (
                    "burn_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("runway_months", models.IntegerField(blank=True, null=True)),
                (
                    "customer_acquisition_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "lifetime_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "churn_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_funding_raised",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "seeking_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("pitch_deck_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_fundraising", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "founder",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "founder"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.industry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
