# Generated by Django 4.2.20 on 2025-08-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_startuptechnology_startuppeople_startupnews_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startuppeople",
            name="company_mission",
            field=models.TextField(blank=True, help_text="Misión de la empresa"),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="company_vision",
            field=models.TextField(blank=True, help_text="Visión de la empresa"),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="founders_count",
            field=models.IntegerField(default=1, help_text="Número de fundadores"),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="hiring_budget_annual",
            field=models.CharField(
                blank=True, help_text="Presupuesto anual de contratación", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="hiring_priority_1",
            field=models.CharField(
                blank=True, help_text="Prioridad #1 de contratación", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="leadership_team_size",
            field=models.IntegerField(
                default=0, help_text="Tamaño del equipo de liderazgo"
            ),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="main_location",
            field=models.CharField(
                blank=True, help_text="Ubicación principal", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="recruitment_strategy",
            field=models.TextField(blank=True, help_text="Estrategia de reclutamiento"),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="tech_team_size",
            field=models.IntegerField(default=0, help_text="Tamaño del equipo técnico"),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="total_employees",
            field=models.IntegerField(default=0, help_text="Total de empleados"),
        ),
        migrations.AddField(
            model_name="startuppeople",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("remote", "Remoto"),
                    ("hybrid", "Híbrido"),
                    ("onsite", "Presencial"),
                ],
                default="hybrid",
                max_length=20,
            ),
        ),
    ]
